/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BkBreadcrumb: typeof import('vue-business-kit')['BkBreadcrumb']
    BkBreadcrumbItem: typeof import('vue-business-kit')['BkBreadcrumbItem']
    BkButton: typeof import('vue-business-kit')['BkButton']
    BkButtonGroup: typeof import('vue-business-kit')['BkButtonGroup']
    BkCollapse: typeof import('vue-business-kit')['BkCollapse']
    BkCollapseItem: typeof import('vue-business-kit')['BkCollapseItem']
    BkDialog: typeof import('vue-business-kit')['BkDialog']
    BkForm: typeof import('vue-business-kit')['BkForm']
    BkFormItem: typeof import('vue-business-kit')['BkFormItem']
    BkIcon: typeof import('vue-business-kit')['BkIcon']
    BkTable: typeof import('vue-business-kit')['BkTable']
    BkTableColumn: typeof import('vue-business-kit')['BkTableColumn']
    BkTag: typeof import("vue-business-kit")["BkTag"]
    DesignGuide: typeof import('./.vitepress/vitepress/components/globals/design-guide.vue')['default']
    EfficiencySvg: typeof import('./.vitepress/vitepress/components/globals/design/efficiency-svg.vue')['default']
    ElementSvg: typeof import('./.vitepress/vitepress/components/globals/design/element-svg.vue')['default']
    LodashSvg: typeof import('./.vitepress/vitepress/components/globals/design/lodash-svg.vue')['default']
    TableColumnItem: typeof import("vue-business-kit")["TableColumnItem"]
    VpApiTyping: typeof import('./.vitepress/vitepress/components/globals/vp-api-typing.vue')['default']
    VpDemo: typeof import('./.vitepress/vitepress/components/vp-demo.vue')['default']
    VpSourceCode: typeof import('./.vitepress/vitepress/components/demo/vp-source-code.vue')['default']
  }
}
