/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DesignGuide: typeof import('./.vitepress/vitepress/components/globals/design-guide.vue')['default']
    EfficiencySvg: typeof import('./.vitepress/vitepress/components/globals/design/efficiency-svg.vue')['default']
    ElementSvg: typeof import('./.vitepress/vitepress/components/globals/design/element-svg.vue')['default']
    EpButton: typeof import('vue-ep-toolkit')['EpButton']
    EpIcon: typeof import('vue-ep-toolkit')['EpIcon']
    EpTable: typeof import('vue-ep-toolkit')['EpTable']
    EpTableColumn: typeof import('vue-ep-toolkit')['EpTableColumn']
    LodashSvg: typeof import('./.vitepress/vitepress/components/globals/design/lodash-svg.vue')['default']
    VpApiTyping: typeof import('./.vitepress/vitepress/components/globals/vp-api-typing.vue')['default']
    VpDemo: typeof import('./.vitepress/vitepress/components/vp-demo.vue')['default']
    VpSourceCode: typeof import('./.vitepress/vitepress/components/demo/vp-source-code.vue')['default']
  }
}
